d-ubuntu:
  ports:
  - 65500:22/tcp
  environment:
    DWL_SSH_ACCESS: 'true'
    DWL_USER_NAME: dwl
    DWL_USER_PASSWD: dwl
    DWL_USER_ID: '1000'
  labels:
    io.rancher.container.start_once: 'true'
    io.rancher.scheduler.affinity:host_label: dwl=dwlComPrivate
  tty: true
  hostname: ubuntu.davaskweblimited.com
  image: davask/d-ubuntu:14.04
  volumes:
  - /home/dwl/projects/factory/docker-dev:/home/dwl
  stdin_open: true
