version: "3"

services:
  app:
    ports:
      - 42002:22/tcp
    environment:
      COMPOSE_PROJECT_NAME: container_name
      DWL_LOCAL_LANG: 'en_US:en'
      DWL_LOCAL: 'en_US.UTF-8'
      DWL_USER_NAME: 'host'
      DWL_USER_PASSWD: 'secretpasssword'
      DWL_USER_ID: '1000'
      DWL_SSH_ACCESS: 'false'
    tty: true
    stdin_open: true
    hostname: localhost
    image: davask/d-debian:8.x
    volumes:
      - ../volumes/home/host:/home/${DWL_USER_NAME:-host}

# docker network create -d bridge --subnet 192.168.0.0/24 --gateway 192.168.0.1 dwlhost
# docker-compose -f /home/$(whoami)/docker-images/base/d-debian/d-debian/docker-compose.yml up -d
